### ISSUE TITLE
root install problem

### ISSUE THREAD

**Issue by guidov** [kirbs-/hide_code#1]
Hi, 
When I try to install as root (on Ubuntu):

Running post install task
Starting hide_code.js install
Unable to install into /usr/lib/python2.7/site-packages/notebook/static/custom
Directory doesn't exist.
Make sure Jupyter is installed.

Install as a user doesn't work either.

My custom directory resides under ~/.jupyter/custom

Is there a way to fix the code to configure custom.js to auto-load hide_code.js in the .jupyter directory?

I have also modified my custom.js so will your install break the original custom.js?

**Comment by guidov** [comment]
just a further comment , would it be possible to do the install similar to how the livereval (RISE) extension is installed?

https://github.com/damianavila/RISE

**Comment by kirbs-** [comment]
Can you try the code below?
```
python -c "import hide_code.hide_code as hc; hc.install('<insert path to custom folder>')"
```
Also, are you sure jupyter is installed for root? You should see it (and notebook) listed if you run ```pip list```.

**Comment by guidov** [comment]
I'm getting these messages:

Also note the error I'm getting under python3

——> python -c "import hide_code.hide_code as hc;
hc.install('/home/user/.jupyter/custom')"
Starting hide_code.js install
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/hide_code/hide_code.py",
line 20, in install
    install_path = np_path
NameError: global name 'np_path' is not defined


——> ipython
Python 3.4.3 (default, Mar 26 2015, 22:03:40)
Type "copyright", "credits" or "license" for more information.

IPython 4.0.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import hide_code.hide_code as hc
  File "/usr/local/lib/python3.4/dist-packages/hide_code/hide_code.py",
line 11
    print 'Starting hide_code.js install'
                                        ^
SyntaxError: Missing parentheses in call to 'print'


In [2]: exit

——> ipython2
Python 2.7.9 (default, Apr  2 2015, 15:33:21)
Type "copyright", "credits" or "license" for more information.

IPython 4.0.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import hide_code.hide_code as hc

In [2]: hc.install('~/.jupyter/custom')
Starting hide_code.js install
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-2-3b047cb9a4c1> in <module>()
----> 1 hc.install('~/.jupyter/custom')

/usr/local/lib/python2.7/dist-packages/hide_code/hide_code.pyc in
install(nb_path, DEBUG)
     18
     19         if nb_path != None:
---> 20                 install_path = np_path
     21                 print "Using " + install_path
     22

NameError: global name 'np_path' is not defined

In [3]:


For the pip installed packages
####################################################################################
——> pip list | grep jupyter
jupyter (1.0.0)
jupyter-client (4.0.0)
jupyter-console (4.0.2)
jupyter-core (4.0.6)

**Comment by kirbs-** [comment]
I think I fixed the issue. Would you download the dev branch, unzip and run ```python setup.py install```?

**Comment by guidov** [comment]
The dev branch works great!

running install_scripts
Running post install task
Starting hide_code.js install
Copying hide_code.js to /home/user/.jupyter/custom
Configured custom.js to auto-load hide_code.js

Thanks, this is a really useful extension.
