### ISSUE TITLE
Support for recent nbconvert and traitlets

### ISSUE THREAD

**Issue by fdion** [kirbs-/hide_code#101]
Issue #92 raised the problem a few years back. The solution was to freeze nbconvert and traitlets. This is not practical anymore, and hide_code needs compatibility with more recent versions (at least 6.x for nbconvert)

#98 is also related.

**Comment by Raudcu** [comment]
Same problem here!

**Comment by canyon289** [comment]
Im running into the same issue, thanks for the help here

**Comment by canyon289** [comment]
Got it working for the newer versions of jupyter notebook
Created a PR here https://github.com/kirbs-/hide_code/pull/102

Until its merged you folks can install off my fork
```
pip install git+https://github.com/canyon289/hide_code.git
```
