### ISSUE TITLE
make hide code persistent 

### ISSUE THREAD

**Issue by Macfly** [kirbs-/hide_code#14]
Hi,
This plugin is really perfect for focusing on the important part of the code.
It could be a good feature to keep the cells hidden or not when sending it to someone else (who has the plugin) or opening the same notebook again.

Thanks for the great job.

**Comment by kirbs-** [comment]
@Macfly this is a bug. The initial notebook rendering should respect the hide code/prompt cell selection. I'll include this with the 0.2.0 release.
