### ISSUE TITLE
html export button does not work when notebook is in path 3 layers deep

### ISSUE THREAD

**Issue by vinhdizzo** [kirbs-/hide_code#18]
On Windows, I get a 404 error similar to what we saw [here](https://github.com/kirbs-/hide_code/issues/5) when I click html export on a notebook that is 4 layers deep: `tree/folder1/folder2/folder3`.  When the notebook is in folder1 or 2, things work.  Thanks.

**Comment by kirbs-** [comment]
I forgot to add this to the documentation. This plugin has to add routes to the various export handlers for each folder level when Jupyter starts. The default is 3 levels deep, with the root folder being level 1. You can change this behavior though using the code below.
```python
from hide_code import HideCodeConfig as c
c.set('nested_params_depth', <number of levels>) # to reach folder3 above set this to 4
```
Then restart Jupyter.
