### ISSUE TITLE
Hides code permanently

### ISSUE THREAD

**Issue by SkyeHarris** [kirbs-/hide_code#24]
- First of all, thanks for the tool! Was working great, but then for some reason it stopped code toggling. 
- I click to show the code, but it does not reappear. 
          - So the situation is that I can run the code, but can't see it, hence can't edit the code. 
             Rebooted and so forth to no avail.

OSx 10.10
python35
notebook 4.2.3
ipython 5.1
jupyter 1

**Comment by kirbs-** [comment]
What version of hide_code are you on? Also, if you open up your browser's console, do you see any error messages when clicking to show the code?

**Comment by SkyeHarris** [comment]
Note: The notebook has two output cells. The top cell toggles, but the bottom output cell does not toggle. So I tried deleting the top output cell, no effect though.


hide_code version = 0.3.1

Don't see errors in console:

loaded custom.jsWatch%20List%20v7.ipynb:121:15
Default extension for cell metadata editing loaded.main.min.js:24136:9
Raw Cell Format toolbar preset loaded.main.min.js:24222:5
Slideshow extension for metadata editing loaded.main.min.js:24270:9
actions jupyter-notebook:find-and-replace does not exist, still binding it in case it will be defined later...main.min.js:29058:17
load_extensions Arguments { , 4 more… }main.min.js:12154:9
Session: kernel_created (beaeae23-27a6-4f59-be74-56766fac9c0b)main.min.js:23424:13
Starting WebSockets: "ws://localhost:8888/api/kernels/23d30314-1fc3-4d02-b5e3-2020102a88a9"main.min.js:22710:9
hide_code setup completehide_code.js:160:2
Loading extension: jupyter-js-widgets/extensionmain.min.js:12131:21
loaded widgetsextension.js:134:14
Kernel: kernel_connected (23d30314-1fc3-4d02-b5e3-2020102a88a9)main.min.js:22357:13
Kernel: kernel_ready (23d30314-1fc3-4d02-b5e3-2020102a88a9)main.min.js:22357:13
Widget backend and frontend versions are compatibleextension.js:32280:22
invisiblehide_code.js:106:12
visiblehide_code.js:103:12
invisiblehide_code.js:106:12
visiblehide_code.js:103:12
invisiblehide_code.js:106:12
visiblehide_code.js:103:12
invisiblehide_code.js:106:12
visiblehide_code.js:103:12
invisible

**Comment by SkyeHarris** [comment]
fyi: I opened the notebook using ( double clicked)...
https://github.com/takluyver/nbopen

**Comment by kirbs-** [comment]
Try deleting the metadata for the cell. Select the metadata cell toolbar, then remove any reference to hideXXX, and save the metadata. You may need to halt and restart the notebook to see any effect. This is a long shot though. I haven't come across the behavior you're seeing before.

**Comment by SkyeHarris** [comment]
Did as directed. No 'hideXXX' found.

As a work around, I downloaded the notebook as  dot py file.
Then copy and pasted the py file code into a new notebook.
The problem has not reoccured.

Will notify, if reoccurs. Appreciate your help!

**Comment by SkyeHarris** [comment]
My mistake. I found 'hideXXX'. Restarted computer. No effect.

**Comment by kirbs-** [comment]
Would you post the metadata from the cell you're having problems with? It sounds like the metadata was corrupted in some way and is causing hide_code to misbehave.

**Comment by SkyeHarris** [comment]
Kirbs,

Since we have communicated, I have created many iterations of the file.
Went thru past files. All are working. So don't know which to provide
metadata for.

**Comment by kirbs-** [comment]
No problem. Reopen this if you experience the problem again.
