### ISSUE TITLE
Output latex file

### ISSUE THREAD

**Issue by allenwoods** [kirbs-/hide_code#31]
Thank you for this great extension! Is there any convinent way to export the latex file used to generate pdf? The raw tex file is useful when writing a report.

**Comment by kirbs-** [comment]
I believe nbconvert supports latex exporting. I'll take a look and add this into the next release.

**Comment by kirbs-** [comment]
@allenwoods this enhancement is available now in the dev branch if you want to test it out. I'll push the update to pypi in a couple of days.

**Comment by kirbs-** [comment]
This feature is available in version 0.5.0.
