### ISSUE TITLE
nbconvert hide_code_html doesn't work

### ISSUE THREAD

**Issue by jykim** [kirbs-/hide_code#33]
I get these warnings and the resulting file still shows the code.

Any suggestions?

$ jupyter nbconvert --to hide_code_html --execute ./MDT\ -\ prod.ipynb
[NbConvertApp] WARNING | Config option `template_path` not recognized by `HideCodeHTMLExporter`.  Did you mean one of: `template_extension, template_file`?
[NbConvertApp] Converting notebook ./MDT - prod.ipynb to hide_code_html
[NbConvertApp] Executing notebook with kernel: python3
[NbConvertApp] Writing 336217 bytes to ./MDT - prod.html
$

**Comment by kirbs-** [comment]
What version of nbconvert are you using?

**Comment by jykim** [comment]
I'm using 4.2.0, installed via pip.

- Jin Young Kim

**Comment by kirbs-** [comment]
I haven't been able to replicate this issue. Do you have any custom configurations you're running?

**Comment by jykim** [comment]
No, just default installation on Ubuntu / Conda 4.2.13.

- Jin Young Kim

**Comment by kirbs-** [comment]
The only thin I can think of is maybe a bad/corrupted install. The error message you posted indicates `template_path` is not recoginized. Check your [HideCodeHTMLExporter](https://github.com/kirbs-/hide_code/blob/9f0943cc4ab5fd33764a6bba59241044a6d92490/hide_code/hide_code_html_exporter.py#L23-L28) class, you should see the template_path property defined there.

**Comment by kirbs-** [comment]
Would you test with version 0.4?

**Comment by chansonZ** [comment]
**same issue**

Python 2.7.13 :: Anaconda 4.4.0 (64-bit)

pip install hide_code
Collecting hide_code
  Downloading hide_code-0.4.0.tar.gz
....
=====================================================
$ jupyter nbconvert --to hide_code_html xxxx.ipynb

[NbConvertApp] WARNING | Config option `template_path` not recognized by `HideCodeHTMLExporter`.  Did you mean one of: `template_extension, template_file`?
Traceback (most recent call last):
  File "/opt/anaconda2/bin/jupyter-nbconvert", line 11, in <module>
    sys.exit(main())
  File "/opt/anaconda2/lib/python2.7/site-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/opt/anaconda2/lib/python2.7/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/opt/anaconda2/lib/python2.7/site-packages/nbconvert/nbconvertapp.py", line 293, in start
    self.convert_notebooks()
  File "/opt/anaconda2/lib/python2.7/site-packages/nbconvert/nbconvertapp.py", line 447, in convert_notebooks
    self.exporter = cls(config=self.config)
  File "/opt/anaconda2/lib/python2.7/site-packages/hide_code/hide_code_html_exporter.py", line 12, in __init__
    super(HideCodeHTMLExporter, self).__init__(config, **kw)
  File "/opt/anaconda2/lib/python2.7/site-packages/nbconvert/exporters/templateexporter.py", line 153, in __init__
    super(TemplateExporter, self).__init__(config=config, **kw)
  File "/opt/anaconda2/lib/python2.7/site-packages/nbconvert/exporters/exporter.py", line 101, in __init__
    self._init_preprocessors()
  File "/opt/anaconda2/lib/python2.7/site-packages/nbconvert/exporters/exporter.py", line 250, in _init_preprocessors
    self.register_preprocessor(preprocessor, enabled=True)
  File "/opt/anaconda2/lib/python2.7/site-packages/nbconvert/exporters/exporter.py", line 211, in register_preprocessor
    preprocessor_cls = import_item(preprocessor)
  File "/opt/anaconda2/lib/python2.7/site-packages/ipython_genutils/importstring.py", line 31, in import_item
    module = __import__(package, fromlist=[obj])
TypeError: Item in ``from list'' must be str, not unicode

**Comment by kirbs-** [comment]
What version of nbconvert are you using?

**Comment by chansonZ** [comment]
**5.2.1**
[root@localhost test]# jupyter nbconvert --version
5.2.1

**Comment by kirbs-** [comment]
Checkout #26. This is due to a change in nbconvert 5.0. Downgrade the package and hide_code should work.
`pip install 'nbconvert==4.3.0' --force-reinstall`

**Comment by kirbs-** [comment]
Also check out https://github.com/jupyter/nbconvert/issues/362.

**Comment by kirbs-** [comment]
@jykim @chansonZ this fix is now in the dev branch if you want to test it out. I'll push the update to pypi in a couple of days.

**Comment by kirbs-** [comment]
This is fixed in version 0.5.0.

**Comment by klBio** [comment]
I have the issue as well with 

jupyter                           1.0.0
jupyter-client                    5.2.4
jupyter-console                   6.0.0
jupyter-contrib-core              0.3.3
jupyter-contrib-nbextensions      0.5.1
jupyter-core                      4.4.0
jupyter-highlight-selected-word   0.2.0
jupyter-latex-envs                1.4.4
jupyter-nbextensions-configurator 0.4.1
jupyterlab                        0.35.3
jupyterlab-server                 0.2.0
notebook                          5.7.4
nbconvert                         5.4.0

I get the 
`WARNING | Config option `template_path` not recognized by `HideCodeHTMLExporter`.  Did you mean one of: `template_extension, template_file`?`
