### ISSUE TITLE
export buttons don't work.

### ISSUE THREAD

**Issue by linas** [kirbs-/hide_code#34]
Clicking on the html export button gives a 404 not found. On the console:
```
[W 18:58:31.068 NotebookApp] 404 GET /notebooks/nalyze/testing-123.ipynb/export/html (127.0.0.1): No such file or directory: nalyze/testing-123.ipynb/export/html
```
As an utter jupyter newbie, I have no clue where to look for additional debug messages.

OS is Debian testing.

**Comment by kirbs-** [comment]
Sounds like the server extensions didn't install properly. Try starting Jupyter with `jupyter notebook --NotebookApp.server_extension="['hide_code.hide_code']"`.

**Comment by linas** [comment]
I did have some install problems when installing hide_code: some dependency was missing; after fixing that, and installing hide_code a second time, the install error messages went away.  It is possible that hide_code is still improperly installed, though; I don't know how to check.

Starting the notebook as you suggests prints the following messages:
```
[W 13:33:29.965 NotebookApp] Config option `server_extension` not recognized by `NotebookApp`.  Did you mean one of: `nbserver_extensions, reraise_server_extension_failures, server_extensions`?
[W 13:33:29.968 NotebookApp] Config option `server_extension` not recognized by `NotebookApp`.  Did you mean one of: `nbserver_extensions, reraise_server_extension_failures, server_extensions`?
[W 13:33:29.972 NotebookApp] Config option `server_extension` not recognized by `NotebookApp`.  Did you mean one of: `nbserver_extensions, reraise_server_extension_failures, server_extensions`?
[W 13:33:29.974 NotebookApp] Config option `server_extension` not recognized by `NotebookApp`.  Did you mean one of: `nbserver_extensions, reraise_server_extension_failures, server_extensions`?
```

So I tried again with `server_extensions` only to get:
```
[W 13:37:06.236 NotebookApp] server_extensions is deprecated, use nbserver_extensions
```
Ignoring this warning, I find that the html export button now works. 

Starting the server with the "recommended" `nbserver_extensions` gives this error:
```
[C 13:39:10.879 NotebookApp] Bad config encountered during initialization:
[C 13:39:10.879 NotebookApp] The 'nbserver_extensions' trait of a NotebookApp instance must be a dict, but a value of class 'list' (i.e. ['hide_code.hide_code']) was specified.
```

The magic invocation is: `jupyter-notebook --NotebookApp.nbserver_extensions="{'hide_code':'hide_code'}"` and that starts the server with no errors; html and pdf export works. 

Thanks!

**Comment by linas** [comment]
FWIW, the above is with Debian `testing`. `jupyter-notebook --version` prints 4.2.3

**Comment by kirbs-** [comment]
That's helpful. Installation problems like yours should go away in the next hide_code release when nbextensions supported.
