### ISSUE TITLE
Code cells not hiding when exporting to slides

### ISSUE THREAD

**Issue by julionaojulho** [kirbs-/hide_code#36]
Hi, thanks for this awesome extension, it is just what I needed.

It works pretty well with another amazing extension, RISE, however when I want to export it to slides, it doesn't properly hide the input cells.

I use the following command to perform the conversion

> jupyter-nbconvert my_file.ipynb --to slides --post serve

Do you have any ideia or any suggestion regarding this issue?

Thanks!

**Comment by kirbs-** [comment]
Exporting to slides isn't supported right now. This extension will hide code/prompts/outputs PDF or HTML exports when using one of the custom exporters. Check out the [documentation](https://github.com/kirbs-/hide_code/wiki/Exporting). I'll add this to the to do list though.

**Comment by julionaojulho** [comment]
Oh, I see.

Thank you very much for your answer. I'm looking forward for the implementation.

**Comment by DavidNemeskey** [comment]
+1 for this feature.

**Comment by kirbs-** [comment]
@julionaojulho @DavidNemeskey this enhancement is available now in the dev branch if you want to test it out. I'll push the update to pypi in a couple of days.

**Comment by kirbs-** [comment]
This feature is available in version 0.5.0.
