### ISSUE TITLE
Hide_code doesn't appear in View -> Cell Toolbar menu

### ISSUE THREAD

**Issue by iguana-luke** [kirbs-/hide_code#37]
Hi,

First off, thanks for sharing the great tool. I hope to be able to enjoy it to produce nice & clean pdf notes. However, I ran into problems. I've installed the extension with no issues, restarted both the jupyter session and the browser but the hide_code toolbar still doesn't appear in the menu. I'm on OS X, Safari, anaconda, Python 2.7, nbconvert 4.2. What can be the problem?

Thanks in advance. Cheers

Luke

**Comment by kirbs-** [comment]
Assuming you're using nbextensions to handle installation, what's the output of `jupyter nbextension list`?

**Comment by iguana-luke** [comment]
Here it is:

`Known nbextensions:
  config dir: /Users/Lukasz/.jupyter/nbconfig
    notebook section
      hide_code/hide_code  enabled 
      - Validating: OK
  config dir: /Users/Lukasz/anaconda/etc/jupyter/nbconfig
    notebook section
      hide_code/hide_code  enabled 
      - Validating: OK`

**Comment by kirbs-** [comment]
Please upgrade to 0.5.0 and check.

**Comment by hugo-pires** [comment]
I have the same problem. Even after upgrade. Could you help me? Thank you

**Comment by kirbs-** [comment]
What does `jupyter nbextension list` show?

**Comment by hugo-pires** [comment]
`Known nbextensions:
  config dir: /home/hugo/.jupyter/nbconfig
    notebook section
      jupyter-js-widgets/extension  enabled 
      - Validating: OK
      hide_code/hide_code  enabled 
      - Validating: OK
  config dir: /home/hugo/anaconda3/etc/jupyter/nbconfig
    notebook section
      hide_code/hide_code  enabled 
      - Validating: OK
`

**Comment by kirbs-** [comment]
With Jupyter running on your local PC, open this url [http://localhost:8890/nbextensions/hide_code/hide_code.js](http://localhost:8888/nbextensions/hide_code/hide_code.js). Does the page load? The first few lines of the page should look like this:
```
/* -*- coding: utf-8 -*-
* ----------------------------------------------------------------------------
* Copyright (c) 2015 - Chris Kirby
*
* Distributed under the terms of the MIT License.
*
* An IPython notebook extension to hide code inputs and prompts for presentation.
* -----------------------------------------------------------------------------
*/

define([
'jquery',
'notebook/js/celltoolbar',
'base/js/namespace'
], 
...
```

**Comment by hugo-pires** [comment]
The page loads correctly. The first lines look like that.

**Comment by kirbs-** [comment]
Look like the plugin installed correctly, but isn't loading in your browser. If you open the web console in your browser, do you see any error messages when opening a notebook.

**Comment by hugo-pires** [comment]
404 Not found
Request URL: http://localhost:8888/static/components/moment/locale/en-gb.js?v=20171110095335

**Comment by kirbs-** [comment]
The last thing you could try is `require(['nbextensions/hide_code'])` in your browser console with a fresh notebook tab open. This should force the web browser to reload the JS file.

**Comment by ZhijieWang** [comment]
For me the notebook is trying to load this link http://localhost:8888/nbextensions/hide_code.js?v=20171205151505

**Comment by shahzeb1** [comment]
@kirbs- I visit that url (http://localhost:8888/nbextensions/hide_code/hide_code.js) and hit a 404. Any way to get this working?

**Comment by kirbs-** [comment]
@ZhijieWang I think notebook is loading the wrong url. The correct url should be http://localhost:8888/nbextensions/hide_code/hide_code.js 

@shahzeb1 the screenshot is of a different plugin. You should see this output of `jupyter nbextension list`

```
Known nbextensions:
  config dir: /Users/kirbs-/.virtualenvs/hide_code/bin/../etc/jupyter/nbconfig
    notebook section
      hide_code/hide_code  enabled 
      - Validating: OK
  config dir: /usr/local/etc/jupyter/nbconfig
    tree section
      ipyparallel/main  enabled 
      - Validating: OK
```

**Comment by kirbs-** [comment]
@ZhijieWang @shahzeb1 @hugo-pires 

Can you try opening your web console and enter `require('nbextensions/hide_code/hide_code')` and post the results.

**Comment by ZhijieWang** [comment]
I somehow get it to work by running the nb-extension setup command in both "sudo" and normal mode.
