### ISSUE TITLE
Markdown Cell Could not revert back when exit hide code model

### ISSUE THREAD

**Issue by BioNinja** [kirbs-/hide_code#4]
when exit the hide code model, markdown cell had add additional cell like this:

### raw markdown cell could not be hided in normal condition
![hide_code_bug](https://cloud.githubusercontent.com/assets/5889336/10266455/d1cda920-6a95-11e5-8108-646eb99f3b52.PNG)

could you fix this?

**Comment by kirbs-** [comment]
As a temporary hack, try hiding the code on the specific markdown cell.
<img width="1146" alt="screen shot 2015-10-04 at 9 32 37 am" src="https://cloud.githubusercontent.com/assets/5613735/10268060/e3596a8c-6a7a-11e5-8878-a9ac6936348e.png">

**Comment by BioNinja** [comment]
Thanks, kirbs. However,  when selected the hide code option for markdown cell, there is still some bug when I want to edit markedown cell.

the **bug** look like this:

select hide code opition as you said, everthing works well:
![Uploading 1.PNG…]()



But addtional bug pops out( the cell toolbar: **None** ), when you doble click the markdown cell, the markdown cell could not be edited. 




the temporary solution is de-selecting the hide code option, and then the markdown cell could be edited again

**Comment by kirbs-** [comment]
@BioNinja would you download the dev branch and see if the issue persists. I've add some logic to ignore markdown cells. That should take care of the issue.
