### ISSUE TITLE
Hidden code is shown in HTML output regardless of visibility toggle

### ISSUE THREAD

**Issue by felciano** [kirbs-/hide_code#40]
I'm having trouble getting `hide_code` to work correctly. The controls seem to work correctly in the UI, and the code cells toggle visibility as expected. However when clicking the "Export to HTML" button, the resulting HTML file always includes the code cells and makes them visible.

I've confirmed I'm using nbconvert 4.3.0, in case that matters.

The log shows
```
Warning: Failed to load file:///var/folders/kj/lwmmwfsd06vgf4vhxq0dc76jr802s3/T/custom.css (ignore)
```
Is it possible this is related to #18 ?

**Comment by kirbs-** [comment]
Is a new window/tab opening up? Also what happens if you use the command line version to export? e.g.`jupyter nbconvert --to hide_code_html notebook_to_convert.ipynb`

**Comment by felciano** [comment]
When I try the command line version I see this error right away:
```
[NbConvertApp] WARNING | Config option `template_path` not recognized by `HideCodeHTMLExporter`.  Did you mean one of: `template_extension, template_file`?
```

**Comment by kirbs-** [comment]
That's helpful. The error message indicates nbconvert 5.x+ is being used instead of 4.3.

**Comment by felciano** [comment]
Strange -- I already did this. Here's what I see if I try again:
```
myuser$ pip install 'nbconvert==4.3.0' --force-reinstall
Requirement already satisfied: nbconvert==4.3.0 in /Users/myuser/.Virtualenvs/content-stats/lib/python2.7/site-packages
```
This seems to confirm it:
```
myuser$ pip list
... (stuff omitted) ...
ipykernel (4.6.1)
ipython (5.4.1)
ipython-genutils (0.2.0)
ipywidgets (7.0.0)
jupyter (1.0.0)
jupyter-client (5.1.0)
jupyter-console (5.2.0)
jupyter-contrib-core (0.3.3)
jupyter-contrib-nbextensions (0.3.1)
jupyter-core (4.3.0)
jupyter-highlight-selected-word (0.0.11)
jupyter-latex-envs (1.3.8.4)
jupyter-nbextensions-configurator (0.2.7)
MarkupSafe (1.0)
... (stuff omitted) ...
nbconvert (4.3.0)
nbformat (4.4.0)
...
```
Any suggestions on how to diagnose this further?

**Comment by kirbs-** [comment]
I'll dig into nbconvert some more. Just to check the obvious, you're running Jupyter from the same virtualenv nbconvert 4.3.0 is installed on, correct?

**Comment by kirbs-** [comment]
Would you try out the dev branch and see if resolves the issue?

**Comment by lwasser** [comment]
Hey there! I am having the same issue with this library. It seems like the perfect solution to writing reports with jupyter notebook which i do with my students. It works for me sometimes and others it doesn't work. Help to help with the troubleshooting if I can post additional information.

**Comment by wino6687** [comment]
Hey everyone, I am also having this issue. Most of the time if I export to html after hiding either all of the code or some of the code, it still appears in the exported doc. I  managed to get one random export to work, but definitely not consistently. I would appreciate any help as this is a great addition to jupyter!

**Comment by kirbs-** [comment]
@lwasser @wino6687 if you post some additional details I can help. Just please create a separate issue if you see a different error message after going through the steps above. Multiple topics in the same issue makes it difficult to manage the process.

The specific issue @felciano mentioned I think is resolved in the dev branch.

**Comment by felciano** [comment]
Hi @kirbs- I'm trying to test it but no luck. Before I debug further, can you confirm that I'm installing from the right place:
```
pip install git+git://github.com/kirbs-/hide_code.git@dev
```

**Comment by kirbs-** [comment]
That looks fine to me. My dev environment isn't in sync with your listed above. I'll sync it up and see if there's a bug in a specific version of package.

**Comment by kirbs-** [comment]
Also what version of notebook are you using?

**Comment by felciano** [comment]
Using jupyter 4.3.0 (assume that is what you mean by notebook)

**Comment by kirbs-** [comment]
Run `pip list | grep notebook`.

**Comment by felciano** [comment]
Notebook 5.0.0

**Comment by kirbs-** [comment]
@felciano would you upgrade to 0.5.0 and check?

**Comment by kirbs-** [comment]
I believe this is fixed now. Closing issue.

**Comment by christophergaughan** [comment]
I don't see the fix

**Comment by kirbs-** [comment]
Please open a new issue and I'll help you there.
