### ISSUE TITLE
Exporting to pdf via Latex can't hide code

### ISSUE THREAD

**Issue by hangyao** [kirbs-/hide_code#41]
I successfully installed and run hide_code, however when exporting to pdf via Latex, the output pdf still show all code in cells.

My system is Windows 7 64-bit, and running Jupyter Notebook from Anaconda environment. hide_code was installed with pip.

Here is the output prompt:

```
[I 10:08:31.360 NotebookApp] hide_code: Starting Latex PDF export for /modelTrai
n.ipynb
[I 10:08:32.926 NotebookApp] Support files will be in
[I 10:08:32.944 NotebookApp] Writing 79518 bytes to notebook.tex
[I 10:08:32.949 NotebookApp] Building PDF
[I 10:08:32.956 NotebookApp] Running pdflatex 3 times: ['pdflatex', 'notebook.te
x']
[I 10:08:38.984 NotebookApp] Running bibtex 1 time: ['bibtex', 'notebook']
[W 10:08:39.107 NotebookApp] b had problems, most likely because there were no c
itations
[I 10:08:39.108 NotebookApp] PDF successfully created
[I 10:08:39.117 NotebookApp] hide_code: Finished Latex PDF export for /modelTrai
n.ipynb
```

It seems like there is an issue, but I don't know how to fix it.

Thank you!

**Comment by kirbs-** [comment]
What version of Jupyter and nbconvert are you using?

**Comment by hangyao** [comment]
@kirbs- 
```
jupyter                   1.0.0                    py36_3
jupyter_client            5.0.1                    py36_0
jupyter_console           5.1.0                    py36_0
jupyter_core              4.3.0                    py36_0
nbconvert                 5.2.1                    py36_0
nbconvert                 4.3.0                     <pip>
```

I set the code to be hidden by both clicking the ```Hide/show code``` button on toolbar, and using ```View -> Cell toolbar -> Hide Code``` menu.

**Comment by hangyao** [comment]
@kirbs-  I don't know why but it works today. Thank you and I will close this issue.

**Comment by chaltik** [comment]
I have this issue on Ubuntu 16.04 and it does not go away (latest install of nbextensions, TexLive and  TexLive-xetex. A hack solution I found on stackoverflow is to use the "Print..." menu in the browser. Works like a charm. But the issue seems to be real.
