### ISSUE TITLE
Images are not included in pdf export

### ISSUE THREAD

**Issue by p2ya** [kirbs-/hide_code#43]
I sue the following code to show images in pdf.
However they just come up as OUT[*] in the pdf following a blank space.

from IPython.display import Image
Image(filename="image.jpg")

I really appreciate if I can get help to fix this.
Also if there is anyway to align the image in centre.

**Comment by kirbs-** [comment]
I'll check it out. Loading images this way should be fine. Also, please post the version of jupyter and notebook you're using.

**Comment by p2ya** [comment]
I was able to add images using nbconvert before but left aligned but through this extension it stopped working.
I use following versions:
Jupyter 4.3.0
Python 2.7.13 :: Anaconda 4.4.0 (x86_64)

**Comment by p2ya** [comment]
Hi Kirbs, did you have a chance to check this out ?

**Comment by kirbs-** [comment]
Looks fine when tested. Are you saving the notebook before attempting to export?

**Comment by p2ya** [comment]
yes the notebook is saved but it doesnt show the images in the pdf.
Can you please show me an example of what you did which worked ?
Was it as a code and using:
from IPython.display import Image
Image(filename="image.jpg")
?

**Comment by p2ya** [comment]
@kirbs- can I have your feedback on this ?

**Comment by kirbs-** [comment]
Do you change any of the default jupyter configuration options in jupyter_notebook_config.py? I can't replicate this on a fresh install of Jupyter and hide_code. Please attach a sample notebook demonstrating the issue.

**Comment by p2ya** [comment]
Hi @kirbs- can I have your versions of jupyter and extension ?

**Comment by kirbs-** [comment]
notebook 5.2.0
jupyter 1.1.0

**Comment by aramhamidi** [comment]
I am having the same problem and I am also using the following lines of code:

from IPython.display import display
img=Image(filename = fileSaveLocation, width = 400,height = 400)
display(img)

JupyterLab 0.31.5
Notebook 5.4.0
OS: windows 10
Anaconda 1.8.3
