### ISSUE TITLE
Markdown with parameter not shown correctly

### ISSUE THREAD

**Issue by p2ya** [kirbs-/hide_code#44]
I use %run to run a python code and define some universal parameters in notebooks.
Also using following in Markdown cells to grab defined parameters from code cells and show as markdown.

**Project:**
{{parameter.replace("_"," ").title()}}

This works nicely in both html and pdf format through nbconvert, but using this extension it comes out as:
Project: {{parameter.replace(“_“,” “).title()}}

However, I expected:
Project: parameter value

**Comment by p2ya** [comment]
@kirbs- can I have your feedback on this ?

**Comment by kirbs-** [comment]
This is a bug/enhancement. I think I'm sanitizing text passed in to markdown cells as a security precaution. I'll take care of this in the next release.

**Comment by kirbs-** [comment]
I don't see this markdown parameter feature in Jupyter. Are you using python-markdown nbextension?

**Comment by kirbs-** [comment]
Closing this for now. I'd like to support this functionality, but parameters in markdown cells isn't support by vanilla Jupyter. Anyone that wants to see this enhancement please open a new issue.
