### ISSUE TITLE
404 Error while exporting to pdf

### ISSUE THREAD

**Issue by ant10484** [kirbs-/hide_code#46]
Hi, 

I have upgraded to hide_code 0.5.  
My problem still persists in that I am able to export my notebook to pdf via the terminal.
But, the buttons on the jupyter notebook doesn't seem to work.
I get 404 error now, where previously I used to get 500 Error.

The following is my output:
[W 00:28:37.636 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20171010002821 (::1) 16.01ms referer=http://localhost:8888/notebooks/Desktop/pythonx/notebooks/Python3_OOP.ipynb
[W 00:28:39.427 NotebookApp] 404 GET /notebooks/Desktop/pythonx/notebooks/Python3_OOP.ipynb/export/pdf (::1): No such file or directory: Desktop/pythonx/notebooks/Python3_OOP.ipynb/export/pdf
[W 00:28:39.434 NotebookApp] 404 GET /notebooks/Desktop/pythonx/notebooks/Python3_OOP.ipynb/export/pdf (::1) 8.51ms referer=http://localhost:8888/notebooks/Desktop/pythonx/notebooks/Python3_OOP.ipynb

Kindly advise.

**Comment by kirbs-** [comment]
I think this is a bug. Do you have a notebook directory manually configured?

**Comment by ant10484** [comment]
No, I haven't configured a directory. I store my notebooks under one directory 'my_notebooks' .

**Comment by stef30360** [comment]
Hello
 Thanks for your works , I,ve same problem.
regards
SR

**Comment by kirbs-** [comment]
@stef30360 please post the console output from jupyter when this error occurs. ty

**Comment by stef30360** [comment]
Hello,  
here are...
[W 21:32:04.642 NotebookApp] 404 GET /notebooks/Dropbox/Kepler/KeplerSoft/_SOURCE_NOTEBOOK_.ipynb/KS_Soft.ipynb/export/pdf (::1): No such file or directory: Dropbox/Kepler/KeplerSoft/_SOURCE_NOTEBOOK_.ipynb/KS_Soft.ipynb/export/pdf
[W 21:32:04.644 NotebookApp] 404 GET /notebooks/Dropbox/Kepler/KeplerSoft/_SOURCE_NOTEBOOK_.ipynb/KS_Soft.ipynb/export/pdf (::1) 3.46ms referer=http://localhost:8888/notebooks/Dropbox/Kepler/KeplerSoft/_SOURCE_NOTEBOOK_.ipynb/KS_Soft.ipynb
[I 21:32:04.819 NotebookApp] Starting buffering for 35b09204-a82d-4494-b369-66745db6db15:82ad4582bd21493c8edcb4bda647273d

**Comment by stef30360** [comment]
hi
I don't understand. When I go back to the file in the source folder, the pdf to latex export works (but without the graphics), however export pdf to html return a 500 error.

**Comment by stef30360** [comment]
yes , when I click on the referrer link, it works.  The root folder Jupyter doesn't contain Dropbox folder.

**Comment by kirbs-** [comment]
@stef30360 just a stab in the dark, but after looking through the output you posted above. Is Jupyter is changing the file path from `http://localhost:8888/notebooks/Dropbox/Kepler/KeplerSoft/_SOURCE_NOTEBOOK_.ipynb/KS_Soft.ipynb` to `http://localhost:8888/notebooks/Dropbox/Kepler/KeplerSoft/SOURCE_NOTEBOOK.ipynb/KS_Soft.ipynb`? Notice the underscores on either side of SOURCE_NOTEBOOK are mising in the later path.

Also, please run the code below and let me know if it's the correct path to the notebook you're using.

```python
import notebook.notebookapp as nb
app = nb.NotebookApp()
print(app.notebook_dir)
```

**Comment by stef30360** [comment]
I changed my file path and I run the code:
`import notebook.notebookapp as nb
app = nb.NotebookApp()
print(app.notebook_dir)`
result: /Users/srmac/Dropbox/Kepler/KeplerSoft/SOURCE_NOTEBOOK
it's a correct path,but I have still the error 404 on the three possible exports.

[W 07:35:59.461 NotebookApp] 404 GET /notebooks/Dropbox/Kepler/KeplerSoft/SOURCE_NOTEBOOK/KS_Soft.ipynb/export/pdf (::1): No such file or directory: Dropbox/Kepler/KeplerSoft/SOURCE_NOTEBOOK/KS_Soft.ipynb/export/pdf
[W 07:35:59.465 NotebookApp] 404 GET /notebooks/Dropbox/Kepler/KeplerSoft/SOURCE_NOTEBOOK/KS_Soft.ipynb/export/pdf (::1) 5.21ms referer=http://localhost:8888/notebooks/Dropbox/Kepler/KeplerSoft/SOURCE_NOTEBOOK/KS_Soft.ipynb
[I 07:35:59.695 NotebookApp] Starting buffering for 0760e978-488a-48e3-b38c-1f038c83b770:c9259ad548854e9a8e2e9e078d4515d3

**Comment by kirbs-** [comment]
Does this link export to pdf? 
http://localhost:8888/notebooks/Dropbox/Kepler/KeplerSoft/SOURCE_NOTEBOOK/KS_Soft.ipynb/export/pdf

**Comment by stef30360** [comment]
Hello, 
Sorry the link doesn't work .

 localhost 8888 notebooks Dropbox Kepler KeplerSoft SOURCE NOTEBOOK Soft ipynb export pdf.
ERR_CONNECTION_REFUSED

**Comment by pixelindigo** [comment]
Same thing. jupyter:4.4.0, hide_code:0.5.0
Jupyter is started from the same dir as report.ipynb
```
[W 13:19:26.516 NotebookApp] 404 GET /notebooks/report.ipynb/export/latexpdf (::1): No such file or directory: report.ipynb/export/latexpdf
[W 13:19:26.520 NotebookApp] 404 GET /notebooks/report.ipynb/export/latexpdf (::1) 4.21ms referer=http://localhost:8888/notebooks/report.ipynb
```

**Comment by kirbs-** [comment]
@pixelindigo thanks, forgot to have the other check this. 404 errors make sense now.

**Comment by kirbs-** [comment]
@stef30360 check hide_code is enabled as a server extension. Run `jupyter serverextension list`.
You should see an output similar to below.
```
config dir: /Users/kirbs-/.jupyter
    hide_code  enabled 
    - Validating...
      hide_code  OK
```
