### ISSUE TITLE
Table of content

### ISSUE THREAD

**Issue by p2ya** [kirbs-/hide_code#47]
This is not an issue but I want to know if we can include the table of content into the pdf conversion.
We have notebooks with TOC which is included in html format and interested to have that in the pdf format as well.

**Comment by p2ya** [comment]
@kirbs- can I have your feedback on this ?

**Comment by kirbs-** [comment]
hide_code will just extends Jupyter's native exporter. This should already work as log as you're adding the TOC to the notebook.
