### ISSUE TITLE
Problems with uninstall hide_code

### ISSUE THREAD

**Issue by JuliaKannenberg** [kirbs-/hide_code#48]
Hi,
I tried the troubleshootings you suggested, but still get an 500 : Internal Server Error.

I want to uninstall hide_code, but I get another error message:
Starting hide_code.js removal...
No config directories contain "custom" folder. Trying Jupyter notebook module path...
Attempting to remove auto-loading for hide_code export handlers.
No hide_code server extensions to remove.

And in your wiki you state: hide_code.uninstall_bootrapped_files().
As I see from the attributes its: hide_code.uninstall_bootstrapped_files()  

Looking forward to your help

**Comment by kirbs-** [comment]
You should be able to `jupyter nbextension uninstall --py hide_code`. You'll need to add `--sys-prefix` if using conda or virtualenv.

**Comment by kirbs-** [comment]
I've updated the uninstall wiki page. Thanks for pointing the typo out.
