### ISSUE TITLE
Compatibility issue with Python-Markdown when creating pdf

### ISSUE THREAD

**Issue by TMorville** [kirbs-/hide_code#51]
When using[ Python-Markdown](https://github.com/Python-Markdown/markdown) to call variables in markdown cells and then using `jupyter nbconvert --to hide_code_pdf experian_report.ipynb` to compile pdf, variables are outputted as {{ var }} instead of the actual number.

In a code cell:
`a = 1.23 ` 

In a markdown cell:
`The result is {{ a }}`

Result in the markdown cell in notebook:
`The result is 1.23`

Result in compiled pdf:
The result is {{ a }}

This does not fail when compiling using `jupyter nbconvert --to pdf notebook.ipynb`

**Comment by kirbs-** [comment]
This is a bug. I'm going to close this issues since it's already being tracked in issue #44.
