### ISSUE TITLE
<title>Notebook</title>

### ISSUE THREAD

**Issue by valentas-kurauskas** [kirbs-/hide_code#62]
Thanks for your useful work! When exporting to HTML Jupyter 5.4.1 puts the correct title, however when exporting via the plugin button (I installed via pip) gives

    <title>Notebook</title>

Also when using "Download as.." for a notebook named with spaces, e.g. "x y z.ipynb", it suggests a correct name "x y z.html", while the plugin suggests "x.html".

**Comment by kirbs-** [comment]
I'll take a look.

**Comment by kirbs-** [comment]
Resolved in 0.5.3.
