### ISSUE TITLE
404: Not Found

### ISSUE THREAD

**Issue by furvusEques** [kirbs-/hide_code#70]
Hello,

I had been using hide_code successfully last week and then must have done something to break it. Here is the output I get when I try to hide all code and export to html

[I 06:42:53.318 NotebookApp] Kernel started: 5b7e89c3-b988-4d25-abdb-a5614e3e8ef3
[I 06:42:53.957 NotebookApp] Adapting to protocol v5.1 for kernel 5b7e89c3-b988-4d25-abdb-a5614e3e8ef3
[I 06:43:20.236 NotebookApp] Starting buffering for 5b7e89c3-b988-4d25-abdb-a5614e3e8ef3:59527a878678425bb011c61dc867ada3
[W 06:43:20.240 NotebookApp] 404 GET /notebooks/STARS/Scripts/python/BMs.ipynb/export/html (::1): No such file or directory: STARS/Scripts/python/BMs.ipynb/export/html
[W 06:43:20.253 NotebookApp] 404 GET /notebooks/STARS/Scripts/python/BMs.ipynb/export/html (::1) 14.33ms referer=http://localhost:8888/notebooks/STARS/Scripts/python/BMs.ipynb
[I 06:43:20.259 NotebookApp] Adapting to protocol v5.1 for kernel 5b7e89c3-b988-4d25-abdb-a5614e3e8ef3
[I 06:43:20.265 NotebookApp] Restoring connection for 5b7e89c3-b988-4d25-abdb-a5614e3e8ef3:59527a878678425bb011c61dc867ada3
[I 06:43:20.279 NotebookApp] Starting buffering for 5b7e89c3-b988-4d25-abdb-a5614e3e8ef3:59527a878678425bb011c61dc867ada3

I read through some of the other issues on the 404 errors and I also checked `jupyter serverextension list` getting:
`hide_code  enabled 
    - Validating...
      hide_code  OK`

I wasn't sure if this was ever resolved, I noticed closed issues but never saw how to fix. Do you have any suggestions on how to fix?

Thanks

**Comment by kirbs-** [comment]
Hey @furvusEques sorry for the delay. Checkout #18. I think this due to your file being a several folders deep from your Jupyter root directory.

**Comment by furvusEques** [comment]
I started it from the same directory and it worked. Thanks for the help and the very useful tool!

**Comment by lwasser** [comment]
oh i just posted a similar issue. i'll try to launch from that directory now...
