### ISSUE TITLE
pip install error (No such file or directory: 'LICENSE')

### ISSUE THREAD

**Issue by chmduquesne** [kirbs-/hide_code#71]
Hi,

When running `pip install hide_code`, I run into the following error:

    Collecting hide_code
      Using cached https://files.pythonhosted.org/packages/04/5b/e0512cf6e62c80c305add427bae8808001163909419e158e92d8c7e4012f/hide_code-0.5.2.tar.gz
    Requirement already satisfied: jupyter in ./venv/lib/python3.5/site-packages (from hide_code) (1.0.0)
    Requirement already satisfied: pdfkit in ./venv/lib/python3.5/site-packages (from hide_code) (0.6.1)
    Requirement already satisfied: nbconvert>=5.0 in ./venv/lib/python3.5/site-packages (from hide_code) (5.4.0)
    Requirement already satisfied: notebook>=5.1 in ./venv/lib/python3.5/site-packages (from hide_code) (5.7.2)
    Requirement already satisfied: ipykernel in ./venv/lib/python3.5/site-packages (from jupyter->hide_code) (5.1.0)
    Requirement already satisfied: jupyter-console in ./venv/lib/python3.5/site-packages (from jupyter->hide_code) (6.0.0)
    Requirement already satisfied: qtconsole in ./venv/lib/python3.5/site-packages (from jupyter->hide_code) (4.4.3)
    Requirement already satisfied: ipywidgets in ./venv/lib/python3.5/site-packages (from jupyter->hide_code) (7.4.2)
    Requirement already satisfied: entrypoints>=0.2.2 in ./venv/lib/python3.5/site-packages (from nbconvert>=5.0->hide_code) (0.2.3)
    Requirement already satisfied: defusedxml in ./venv/lib/python3.5/site-packages (from nbconvert>=5.0->hide_code) (0.5.0)
    Requirement already satisfied: jinja2 in ./venv/lib/python3.5/site-packages (from nbconvert>=5.0->hide_code) (2.10)
    Requirement already satisfied: jupyter-core in ./venv/lib/python3.5/site-packages (from nbconvert>=5.0->hide_code) (4.4.0)
    Requirement already satisfied: nbformat>=4.4 in ./venv/lib/python3.5/site-packages (from nbconvert>=5.0->hide_code) (4.4.0)
    Requirement already satisfied: traitlets>=4.2 in ./venv/lib/python3.5/site-packages (from nbconvert>=5.0->hide_code) (4.3.2)
    Requirement already satisfied: bleach in ./venv/lib/python3.5/site-packages (from nbconvert>=5.0->hide_code) (3.0.2)
    Requirement already satisfied: mistune>=0.8.1 in ./venv/lib/python3.5/site-packages (from nbconvert>=5.0->hide_code) (0.8.4)
    Requirement already satisfied: pandocfilters>=1.4.1 in ./venv/lib/python3.5/site-packages (from nbconvert>=5.0->hide_code) (1.4.2)
    Requirement already satisfied: testpath in ./venv/lib/python3.5/site-packages (from nbconvert>=5.0->hide_code) (0.4.2)
    Requirement already satisfied: pygments in ./venv/lib/python3.5/site-packages (from nbconvert>=5.0->hide_code) (2.3.0)
    Requirement already satisfied: Send2Trash in ./venv/lib/python3.5/site-packages (from notebook>=5.1->hide_code) (1.5.0)
    Requirement already satisfied: ipython-genutils in ./venv/lib/python3.5/site-packages (from notebook>=5.1->hide_code) (0.2.0)
    Requirement already satisfied: tornado>=4 in ./venv/lib/python3.5/site-packages (from notebook>=5.1->hide_code) (5.1.1)
    Requirement already satisfied: jupyter-client>=5.2.0 in ./venv/lib/python3.5/site-packages (from notebook>=5.1->hide_code) (5.2.3)
    Requirement already satisfied: prometheus-client in ./venv/lib/python3.5/site-packages (from notebook>=5.1->hide_code) (0.4.2)
    Requirement already satisfied: terminado>=0.8.1 in ./venv/lib/python3.5/site-packages (from notebook>=5.1->hide_code) (0.8.1)
    Requirement already satisfied: pyzmq>=17 in ./venv/lib/python3.5/site-packages (from notebook>=5.1->hide_code) (17.1.2)
    Requirement already satisfied: ipython>=5.0.0 in ./venv/lib/python3.5/site-packages (from ipykernel->jupyter->hide_code) (7.2.0)
    Requirement already satisfied: prompt-toolkit<2.1.0,>=2.0.0 in ./venv/lib/python3.5/site-packages (from jupyter-console->jupyter->hide_code) (2.0.7)
    Requirement already satisfied: widgetsnbextension~=3.4.0 in ./venv/lib/python3.5/site-packages (from ipywidgets->jupyter->hide_code) (3.4.2)
    Requirement already satisfied: MarkupSafe>=0.23 in ./venv/lib/python3.5/site-packages (from jinja2->nbconvert>=5.0->hide_code) (1.1.0)
    Requirement already satisfied: jsonschema!=2.5.0,>=2.4 in ./venv/lib/python3.5/site-packages (from nbformat>=4.4->nbconvert>=5.0->hide_code) (2.6.0)
    Requirement already satisfied: six in ./venv/lib/python3.5/site-packages (from traitlets>=4.2->nbconvert>=5.0->hide_code) (1.11.0)
    Requirement already satisfied: decorator in ./venv/lib/python3.5/site-packages (from traitlets>=4.2->nbconvert>=5.0->hide_code) (4.3.0)
    Requirement already satisfied: webencodings in ./venv/lib/python3.5/site-packages (from bleach->nbconvert>=5.0->hide_code) (0.5.1)
    Requirement already satisfied: python-dateutil>=2.1 in ./venv/lib/python3.5/site-packages (from jupyter-client>=5.2.0->notebook>=5.1->hide_code) (2.7.5)
    Requirement already satisfied: ptyprocess; os_name != "nt" in ./venv/lib/python3.5/site-packages (from terminado>=0.8.1->notebook>=5.1->hide_code) (0.6.0)
    Requirement already satisfied: setuptools>=18.5 in ./venv/lib/python3.5/site-packages (from ipython>=5.0.0->ipykernel->jupyter->hide_code) (40.6.2)
    Requirement already satisfied: backcall in ./venv/lib/python3.5/site-packages (from ipython>=5.0.0->ipykernel->jupyter->hide_code) (0.1.0)
    Requirement already satisfied: jedi>=0.10 in ./venv/lib/python3.5/site-packages (from ipython>=5.0.0->ipykernel->jupyter->hide_code) (0.13.1)
    Requirement already satisfied: pexpect; sys_platform != "win32" in ./venv/lib/python3.5/site-packages (from ipython>=5.0.0->ipykernel->jupyter->hide_code) (4.6.0)
    Requirement already satisfied: pickleshare in ./venv/lib/python3.5/site-packages (from ipython>=5.0.0->ipykernel->jupyter->hide_code) (0.7.5)
    Requirement already satisfied: wcwidth in ./venv/lib/python3.5/site-packages (from prompt-toolkit<2.1.0,>=2.0.0->jupyter-console->jupyter->hide_code) (0.1.7)
    Requirement already satisfied: parso>=0.3.0 in ./venv/lib/python3.5/site-packages (from jedi>=0.10->ipython>=5.0.0->ipykernel->jupyter->hide_code) (0.3.1)
    Building wheels for collected packages: hide-code
      Running setup.py bdist_wheel for hide-code ... error
      Complete output from command /home/cduquesne/code/perso/data-science-exercises/venv/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-1r79eijb/hide-code/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-0uxkuyk2 --python-tag cp35:
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib
      creating build/lib/hide_code
      copying hide_code/hide_code_config.py -> build/lib/hide_code
      copying hide_code/hide_code_preprocessor.py -> build/lib/hide_code
      copying hide_code/hide_code_html_exporter.py -> build/lib/hide_code
      copying hide_code/hide_code_slides_exporter.py -> build/lib/hide_code
      copying hide_code/utils.py -> build/lib/hide_code
      copying hide_code/hide_code_latex_exporter.py -> build/lib/hide_code
      copying hide_code/__init__.py -> build/lib/hide_code
      copying hide_code/hide_code_pdf_exporter.py -> build/lib/hide_code
      copying hide_code/hide_code.py -> build/lib/hide_code
      copying hide_code/hide_code.js -> build/lib/hide_code
      copying hide_code/auto-load.txt -> build/lib/hide_code
      copying hide_code/LICENSE.txt -> build/lib/hide_code
      copying hide_code/auto-load-server-extension.txt -> build/lib/hide_code
      creating build/lib/hide_code/Templates
      copying hide_code/Templates/hide_code_basic.tpl -> build/lib/hide_code/Templates
      copying hide_code/Templates/hide_code_full.tpl -> build/lib/hide_code/Templates
      copying hide_code/Templates/hide_code_slides.tpl -> build/lib/hide_code/Templates
      copying hide_code/Templates/hide_code_article.tplx -> build/lib/hide_code/Templates
      copying hide_code/Templates/hide_code_base_style.tplx -> build/lib/hide_code/Templates
      copying hide_code/hide_code_config.json -> build/lib/hide_code
      installing to build/bdist.linux-x86_64/wheel
      running install
      running install_lib
      creating build/bdist.linux-x86_64
      creating build/bdist.linux-x86_64/wheel
      creating build/bdist.linux-x86_64/wheel/hide_code
      copying build/lib/hide_code/auto-load.txt -> build/bdist.linux-x86_64/wheel/hide_code
      copying build/lib/hide_code/LICENSE.txt -> build/bdist.linux-x86_64/wheel/hide_code
      copying build/lib/hide_code/hide_code_config.py -> build/bdist.linux-x86_64/wheel/hide_code
      copying build/lib/hide_code/hide_code_preprocessor.py -> build/bdist.linux-x86_64/wheel/hide_code
      copying build/lib/hide_code/hide_code_html_exporter.py -> build/bdist.linux-x86_64/wheel/hide_code
      copying build/lib/hide_code/hide_code_slides_exporter.py -> build/bdist.linux-x86_64/wheel/hide_code
      copying build/lib/hide_code/utils.py -> build/bdist.linux-x86_64/wheel/hide_code
      copying build/lib/hide_code/auto-load-server-extension.txt -> build/bdist.linux-x86_64/wheel/hide_code
      creating build/bdist.linux-x86_64/wheel/hide_code/Templates
      copying build/lib/hide_code/Templates/hide_code_basic.tpl -> build/bdist.linux-x86_64/wheel/hide_code/Templates
      copying build/lib/hide_code/Templates/hide_code_full.tpl -> build/bdist.linux-x86_64/wheel/hide_code/Templates
      copying build/lib/hide_code/Templates/hide_code_slides.tpl -> build/bdist.linux-x86_64/wheel/hide_code/Templates
      copying build/lib/hide_code/Templates/hide_code_article.tplx -> build/bdist.linux-x86_64/wheel/hide_code/Templates
      copying build/lib/hide_code/Templates/hide_code_base_style.tplx -> build/bdist.linux-x86_64/wheel/hide_code/Templates
      copying build/lib/hide_code/hide_code_latex_exporter.py -> build/bdist.linux-x86_64/wheel/hide_code
      copying build/lib/hide_code/__init__.py -> build/bdist.linux-x86_64/wheel/hide_code
      copying build/lib/hide_code/hide_code_pdf_exporter.py -> build/bdist.linux-x86_64/wheel/hide_code
      copying build/lib/hide_code/hide_code.py -> build/bdist.linux-x86_64/wheel/hide_code
      copying build/lib/hide_code/hide_code.js -> build/bdist.linux-x86_64/wheel/hide_code
      copying build/lib/hide_code/hide_code_config.json -> build/bdist.linux-x86_64/wheel/hide_code
      running install_egg_info
      running egg_info
      writing requirements to hide_code.egg-info/requires.txt
      writing dependency_links to hide_code.egg-info/dependency_links.txt
      writing hide_code.egg-info/PKG-INFO
      writing entry points to hide_code.egg-info/entry_points.txt
      writing top-level names to hide_code.egg-info/top_level.txt
      reading manifest file 'hide_code.egg-info/SOURCES.txt'
      writing manifest file 'hide_code.egg-info/SOURCES.txt'
      Copying hide_code.egg-info to build/bdist.linux-x86_64/wheel/hide_code-0.5.2-py3.5.egg-info
      running install_scripts
      error: [Errno 2] No such file or directory: 'LICENSE'
      
      ----------------------------------------
      Failed building wheel for hide-code
      Running setup.py clean for hide-code
    Failed to build hide-code
    Installing collected packages: hide-code
      Running setup.py install for hide-code ... done
    Successfully installed hide-code-0.5.2
    
Now the extension works nonetheless, but I figured I would still file an issue for the error.

Have a good day!

**Comment by lwasser** [comment]
+1 i had the same issue installing! but it generally works!

**Comment by kirbs-** [comment]
I'll check it out. I didn't do much testing when @toddrme2178 submitted the PR to add the license to the wheel distributions.

**Comment by fcrescio** [comment]
I had the same issue today, it downloaded the version:
`Collecting hide_code
  Downloading https://files.pythonhosted.org/packages/04/5b/e0512cf6e62c80c305add427bae8808001163909419e158e92d8c7e4012f/hide_code-0.5.2.tar.gz`

then failed installation because of:

`
running install_scripts
  error: [Errno 2] No such file or directory: 'LICENSE'
`

**Comment by GalvinGao** [comment]
+1 for here. I just ignored the error and try to enable everything (go to step 2, 3, 4 of `README.md`), and I've been given no errors. It might works but, *do it at your own risk*.

**Comment by ms440** [comment]
+1. Annoying. Please, take a look.
