### ISSUE TITLE
Hide code export issues

### ISSUE THREAD

**Issue by lwasser** [kirbs-/hide_code#72]
Hi there!
This is a really great package. I'm having some export issues. Here is what i tried
-  when i click on the export buttons for pdf, html  etc i get a page not found error
<img width="757" alt="screen shot 2018-12-12 at 5 37 12 pm" src="https://user-images.githubusercontent.com/7649194/49907715-a84a5b80-fe34-11e8-81e9-bc77d9d09777.png">
NOTE: this error is fixed if i launch jupyter from the directory where my files live. But often i'm not working in that directory. It's a nice fix for now however! -- [noting this issue](https://github.com/kirbs-/hide_code/issues/70)

- If i try to use the CLI to run this `jupyter nbconvert --to html create_legend_test-Copy1.ipynb` the output html file still has the code, plots etc that i have hidden so it ignores the metadata to hide things. note that i did save the file and confirmed the tags were in the cell metadata. 

Any ideas why this might be happening? i'd be pretty excited to use this in my classes - the students create reports! Many thanks!

**Comment by windnage** [comment]
I am also seeing this issue, however, even when I launch jupyter from the directory where the notebook lives, I still get a 404 not found error.

**Comment by kirbs-** [comment]
@lwasser to use with nbconvert CLI use `--to hide_code_html`. In the command above you're calling nbconvert's stock html converter.

I'll checkout the other issue though. Have you tried setting notebook_dir parameter when starting Jupyter?

**Comment by lwasser** [comment]
ahhhhh @kirbs-  my apologies - i should have known that was a stock nbconvert export call not hide_code. Thank you. I will try it again using `--to hide_code_html` !! Thank you.

As for the notebook_dir parameter. can you please direct me to / or tell me how i would set that? i'll try it. My students are using this package in class and most of them ran into this 404 error issue.
