### ISSUE TITLE
Does this work in jupyter lab?

### ISSUE THREAD

**Issue by nevion** [kirbs-/hide_code#75]
It installs but I can't figure out how to use it's functionalities there

**Comment by montoyah** [comment]
Same here. Does it work at all on Jupyter Lab?

Cheers!

**Comment by kirbs-** [comment]
I'll check, but I doubt it. If there's interest I'll add support.

**Comment by nevion** [comment]
@kirbs- definitely interested , still trying to find a workflow that doesn't involve firefox html editing away code cells for output pdf / html

**Comment by skost01** [comment]
@kirbs- I would also be very interested in a labextension

**Comment by Alchemication** [comment]
@kirbs- This would be a great addition to Lab. Currently the only reason for me to use old Jupyter are slidedecks (RISE) and clean hiding code extension

**Comment by kirbs-** [comment]
I'm finally getting around to supporting Jupyter Lab with this extension. It may take a while though. I've got to get up the learning curve on Lab's new architecture. It's pretty different than classic notebook.

**Comment by nevion** [comment]
yea understood, still would find useful - I still haven't found a good way otherwise.

**Comment by montoyah** [comment]
Thanks Kirbs. How can I help?

**Comment by kirbs-** [comment]
Hi all, I'm looking for a couple of people to test the extension for Jupyter Lab. You should be able to install it using JL's built in extension by searching for @kirbs. The extension is compatible with notebooks created with classic Jupyter notebook. It also requires having hide_code server extensions installed.

<img width="350" alt="image" src="https://user-images.githubusercontent.com/5613735/98311991-bfe9da80-1f9e-11eb-847f-65347cf6d0f4.png">

Usage is a little different. JL removed the cell toolbar from notebooks so the check boxes to hide components are gone. In their place are three toolbar buttons on the right to toggle code, output and prompt hiding (respectively) on the **currently selected cells**. 

![image](https://user-images.githubusercontent.com/5613735/98312637-26bbc380-1fa0-11eb-9740-68f96d7aee8f.png)

Lastly, exporting works as expected, but triggering exporting has changed to use JL standard "Export Notebook As" menu.
![image](https://user-images.githubusercontent.com/5613735/98312918-ad70a080-1fa0-11eb-909c-e8cc61bc961b.png)

Please open a new issue if you find any bugs. Appreciate the help!

**Comment by nevion** [comment]
where does hide_code_lab come from?  Was prompted to install it via pip but pypi doesn't show it.

**Comment by kirbs-** [comment]
Ah, must of missed a setting somewhere. I'll push a new version to npm.

**Comment by nevion** [comment]
Probably more unique to me but:

[W 14:51:52.837 LabApp] Failed to fetch package metadata for '@kirbs/hide_code': URLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)'))

Any thoughts on how to disable this SSL verification error I'm seeing while running the jupyter lab server?

**Comment by kirbs-** [comment]
You can try `jupyter labextension install @kirbs/hide_code`, but it probably won't work. This error is usually caused by missing CA certficates. You can try updating standard root CAs with [certifi or Install Certificates.command on MacOS](https://stackoverflow.com/questions/50236117/scraping-ssl-certificate-verify-failed-error-for-http-en-wikipedia-org). If you're on a corporate VPN or proxy, you'll need to get the root CA certificate and manually install it.

**Comment by kirbs-** [comment]
Experimental support available in 0.6.0. Please open a new issue for any bugs/problems.
