### ISSUE TITLE
Hide Code: Cannot Export to PDF but HTML works

### ISSUE THREAD

**Issue by sachn1** [kirbs-/hide_code#76]
I installed hide code and also all pre-requisites as mentioned. I am able to export the notebook to HTML format but not PDF. It shows **500: Internal Server Error**. I have been following similar issues that had been raised before in the platform but unfortunately, I could no get my issue resolved. 

I ran in the normal scenario where it was throwing the error mentioned above. Then, following various other issues raised, I ran `jupyter notebook --NotebookApp.server_extensions="['hide_code.hide_code']"`, but still, I could not understand the root cause of it. However, ran the above code for once and clicked on the button to export it as PDF, and the output of it (generated on the prompt) is shown below.

(base) C:\Users\Sachin Nandakumar>jupyter notebook --NotebookApp.server_extensions="['hide_code.hide_code']"
[W 23:59:22.073 NotebookApp] server_extensions is deprecated, use nbserver_extensions
[I 23:59:22.397 NotebookApp] hide_code: Attempting to load hid_code export handler extensions.
[I 23:59:22.398 NotebookApp] hide_code: Hide_code export handler extensions loaded.
[I 23:59:22.398 NotebookApp] hide_code: Attempting to load hid_code export handler extensions.
[I 23:59:22.399 NotebookApp] hide_code: Hide_code export handler extensions loaded.
[I 23:59:22.427 NotebookApp] JupyterLab extension loaded from C:\Users\Sachin Nandakumar\Anaconda3\lib\site-packages\jupyterlab
[I 23:59:22.427 NotebookApp] JupyterLab application directory is C:\Users\Sachin Nandakumar\Anaconda3\share\jupyter\lab
[I 23:59:22.429 NotebookApp] Serving notebooks from local directory: C:\Users\Sachin Nandakumar
[I 23:59:22.429 NotebookApp] The Jupyter Notebook is running at:
[I 23:59:22.429 NotebookApp] http://localhost:8888/?token=bdcecb027ef2fdad17f2c58a2a033ae395422ec1a6e002dc
[I 23:59:22.429 NotebookApp]  or http://127.0.0.1:8888/?token=bdcecb027ef2fdad17f2c58a2a033ae395422ec1a6e002dc
[I 23:59:22.430 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 23:59:22.487 NotebookApp]

    To access the notebook, open this file in a browser:
        file:///C:/Users/Sachin%20Nandakumar/AppData/Roaming/jupyter/runtime/nbserver-13816-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=bdcecb027ef2fdad17f2c58a2a033ae395422ec1a6e002dc
     or http://127.0.0.1:8888/?token=bdcecb027ef2fdad17f2c58a2a033ae395422ec1a6e002dc
[E 23:59:23.773 NotebookApp] Could not open static file ''
[W 23:59:23.809 NotebookApp] 404 GET /static/components/react/react-dom.production.min.js (::1) 8.61ms referer=http://localhost:8888/tree?token=bdcecb027ef2fdad17f2c58a2a033ae395422ec1a6e002dc
[W 23:59:23.929 NotebookApp] 404 GET /static/components/react/react-dom.production.min.js (::1) 1.24ms referer=http://localhost:8888/tree?token=bdcecb027ef2fdad17f2c58a2a033ae395422ec1a6e002dc
[W 00:02:21.858 NotebookApp] 404 GET /static/components/react/react-dom.production.min.js (::1) 2.48ms referer=http://localhost:8888/notebooks/try/try.ipynb
[W 00:02:21.921 NotebookApp] 404 GET /static/components/react/react-dom.production.min.js (::1) 1.56ms referer=http://localhost:8888/notebooks/try/try.ipynb
[W 00:02:22.099 NotebookApp] Notebook try/try.ipynb is not trusted
[I 00:02:22.392 NotebookApp] Kernel started: b2164087-46c3-4a75-909d-b34795350eb0
[I 00:02:23.032 NotebookApp] Adapting from protocol version 5.1 (kernel b2164087-46c3-4a75-909d-b34795350eb0) to 5.3 (client).
[I 00:02:26.815 NotebookApp] Starting buffering for b2164087-46c3-4a75-909d-b34795350eb0:d805e33af0e54de4895b61c0a7cabe64
[I 00:02:26.825 NotebookApp] Adapting from protocol version 5.1 (kernel b2164087-46c3-4a75-909d-b34795350eb0) to 5.3 (client).
[I 00:02:26.826 NotebookApp] hide_code: Starting PDF export for None
INFO: Could not find files for the given pattern(s).
[E 00:02:27.064 NotebookApp] Uncaught exception GET /notebooks/try/try.ipynb/export/pdf (::1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/notebooks/try/try.ipynb/export/pdf', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "C:\Users\Sachin Nandakumar\Anaconda3\lib\site-packages\pdfkit\configuration.py", line 21, in __init__
        with open(self.wkhtmltopdf) as f:
    FileNotFoundError: [Errno 2] No such file or directory: b''

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Users\Sachin Nandakumar\Anaconda3\lib\site-packages\tornado\web.py", line 1697, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "C:\Users\Sachin Nandakumar\Anaconda3\lib\site-packages\hide_code\hide_code.py", line 44, in get
        output = pdfkit.from_string(output_html, False)
      File "C:\Users\Sachin Nandakumar\Anaconda3\lib\site-packages\pdfkit\api.py", line 70, in from_string
        configuration=configuration, cover_first=cover_first)
      File "C:\Users\Sachin Nandakumar\Anaconda3\lib\site-packages\pdfkit\pdfkit.py", line 42, in __init__
        self.configuration = (Configuration() if configuration is None
      File "C:\Users\Sachin Nandakumar\Anaconda3\lib\site-packages\pdfkit\configuration.py", line 27, in __init__
        'https://github.com/JazzCore/python-pdfkit/wiki/Installing-wkhtmltopdf' % self.wkhtmltopdf)
    OSError: No wkhtmltopdf executable found: "b''"
    If this file exists please check that this process can read it. Otherwise please install wkhtmltopdf - https://github.com/JazzCore/python-pdfkit/wiki/Installing-wkhtmltopdf
[E 00:02:27.067 NotebookApp] {
      "Host": "localhost:8888",
      "Connection": "keep-alive",
      "Upgrade-Insecure-Requests": "1",
      "Dnt": "1",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36",
      "Sec-Fetch-Mode": "navigate",
      "Sec-Fetch-User": "?1",
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3",
      "Sec-Fetch-Site": "same-origin",
      "Referer": "http://localhost:8888/notebooks/try/try.ipynb",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en-US,en;q=0.9",
      "Cookie": "_xsrf=2|2b448b09|cb762ea3deb8a38805f934fabc1a2b79|1564302829; username-localhost-8890=\"2|1:0|10:1564310153|23:username-localhost-8890|44:OWJjNzczODBkNjY4NGU1ZmI5MjczZGNlODdlZjczZDM=|f4fb8d43c797667dbee1f205747d9cb936cc90b703583b30c5003ad1dd523437\"; username-localhost-8891=\"2|1:0|10:1564312641|23:username-localhost-8891|44:YThkMmNkNzU2NDYzNDk1ZmEwNmM1ZjM4ZDI5ZDRlZTA=|7affbee61f73160f16cc561c9c7712d80366a23fa5b7c99e6d380b14f927f9cc\"; username-localhost-8889=\"2|1:0|10:1565733301|23:username-localhost-8889|44:MmY1NDZjZWYyMTc3NDgzZDg4ZmRmY2ZjMjQyMjkxNjA=|bc2eaf1fe147d0285d64e9838b4b3360e56272c0ae7ec2c10fef506e419b16b3\"; username-localhost-8888=\"2|1:0|10:1565733563|23:username-localhost-8888|44:OGFkMGI2MWNjY2IxNGNkNTg1MDdiY2QwNjQ1ODE5ZTk=|879462b25eb9c13cd2da279a5d8f6443b067608ec2137f807e9b24a19e1333bb\""
    }
[E 00:02:27.067 NotebookApp] 500 GET /notebooks/try/try.ipynb/export/pdf (::1) 241.02ms referer=http://localhost:8888/notebooks/try/try.ipynb
[I 00:02:27.069 NotebookApp] Restoring connection for b2164087-46c3-4a75-909d-b34795350eb0:d805e33af0e54de4895b61c0a7cabe64
[I 00:02:27.073 NotebookApp] Starting buffering for b2164087-46c3-4a75-909d-b34795350eb0:d805e33af0e54de4895b61c0a7cabe64
[W 00:02:27.083 NotebookApp] 404 GET /static/components/react/react-dom.production.min.js (::1) 1.55ms referer=http://localhost:8888/notebooks/try/try.ipynb/export/pdf
[W 00:02:27.136 NotebookApp] 404 GET /static/components/react/react-dom.production.min.js (::1) 1.99ms referer=http://localhost:8888/notebooks/try/try.ipynb/export/pdf

**Comment by kirbs-** [comment]
Is wkhtmltopdf installed? Also, please post your jupyter notebook version.

thanks
