### ISSUE TITLE
Export to HTML and PDF still with the output

### ISSUE THREAD

**Issue by XueWang2019** [kirbs-/hide_code#79]
My issue is: the hide code works fine with Notebook, but when exporting to HTML or PDF, the outputs are still there. Then I checked the configurable nbextensions for hide_code/hide_code, the info is "This nbextension is enabled in the notebook json config, but doesn't provide a yaml file to tell us how to configure it. You can still enable or disable it from here, though." 
I am not sure whether it is the reason. May I ask for your help for it? Thanks.

**Comment by kirbs-** [comment]
How are you exporting? and can you post the versions of nbconvert, notebook and jupyter your using?

**Comment by XueWang2019** [comment]
I use below method to export the file:
File->Download as->PDF via Latex(.pdf)
The versions as below:
<img width="328" alt="nbconvert" src="https://user-images.githubusercontent.com/50823387/69147335-01555180-0ad2-11ea-9c8c-abf0bb20153e.PNG">
<img width="405" alt="jupter" src="https://user-images.githubusercontent.com/50823387/69147408-23e76a80-0ad2-11ea-95e5-9d8f7285fa38.PNG">
Thanks.

**Comment by kirbs-** [comment]
Hide_code adds a new menu download menu with the various export formats. Try those.

**Comment by XueWang2019** [comment]
Thank you.
Now it is much better. 

- It works for this function like df.head(), 

![image](https://user-images.githubusercontent.com/50823387/69501559-50eab180-0f06-11ea-9e62-e50147f0f5f3.png)


-  but it doesn't work like below:

![image](https://user-images.githubusercontent.com/50823387/69501532-2862b780-0f06-11ea-91a5-0165514a1ae2.png)

**Comment by XueWang2019** [comment]
Yes, it works. Thank you very much!

**Comment by a7906375** [comment]
Hi When i try the new menu i get an error message that say you have requested a page that doesn't exists! Any idea why would this be the case. The new menu appears across the top. Any help would be appreciated. Thanks

**Comment by kirbs-** [comment]
Please open a new issue and I'll help you there.
