### ISSUE TITLE
Hide code : Support for letters with accent marks

### ISSUE THREAD

**Issue by ouyqf** [kirbs-/hide_code#80]
Hi, 

First of all, I'd like to thank the contributors of Hide code. It is an excellent extension for hiding codes when exporting notebook as html files.

But recently, I met a problem about the format in the exported html files. In fact, all the letters with accent marks like é,è,à, etc. were exported with a bad format. Here is an exemple to show the issue that I had : 

The output that I wish :  Fériés
The one I had in my html file : FÃ©riÃ©s

Could some one tell me how to solve this problem please ?

Thanks a lot.

Best wish,

ouy

**Comment by kirbs-** [comment]
@ouyqf would you install the dev branch and see if your issue is resolved?

**Comment by kirbs-** [comment]
Resolved in 0.5.3.
