### ISSUE TITLE
Install with Conda

### ISSUE THREAD

**Issue by NEGU93** [kirbs-/hide_code#88]
When trying to install it with anaconda I have the following issue:

`pip install hide_code`: This works well.

`jupyter nbextension install --py hide_code` throws: 

`PermissionError: [Errno 13] Permission denied: '/usr/local/share/jupyter'`

So I try sudo: 
```
sudo jupyter nbextension install --py hide_code
sudo: jupyter: command not found
```
Last issue is because of [this](https://askubuntu.com/questions/588497/sudo-conda-command-not-found).

How can I install this feature using conda?

**Comment by kirbs-** [comment]
Try add --sys-prefix to jupyter nbextension to install into virtualenv or conda environment.
