### ISSUE TITLE
Exporting result in 404 error on Jupyterhub

### ISSUE THREAD

**Issue by brospars** [kirbs-/hide_code#90]
Hello,

since I updated to v0.5.3 or v0.5.5 (even tried to install v0.5.6 from `dev` branch) I get 404 error when exporting notebooks using hide_code on Jupyterhub. It was working fine in v0.5.2 but now I get an error when installing this version (`cannot build wheel` or something like this).

My hub is located on a 'subfolder' of the server and the hide_code export url looks like this : 
`https://domain.com/folder/jupyter/user/uid/notebooks/work/module2/exo1/notebook.ipynb/export/pdf`

Any idea how to solve this ?

**Comment by kirbs-** [comment]
hide_code isn't tested with jupyterlab. Support is on the roadmap though.
