### ISSUE TITLE
Can't install into an empty virtual environment

### ISSUE THREAD

**Issue by rjmorris** [kirbs-/hide_code#97]
Attempting to install hide_code into an empty virtual environment results in an error, because the `notebook` package isn't already installed. This same bug was reported in #87. In that issue, the author suggested that the problem was resolved in v0.6.0 by installing as `pip install hide_code[all]`. However, I don't think that fixed the problem.

Steps to reproduce:

```
$ python -m venv venv
$ source venv/bin/activate
$ pip install hide_code[all]
Collecting hide_code[all]
  Using cached hide_code-0.6.0.tar.gz (62 kB)
    ERROR: Command errored out with exit status 1:
     command: /home/rjmorris/scratch/hide_code_py/venv/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-wja8lnas/hide-code/setup.py'"'"'; __file__='"'"'/tmp/pip-install-wja8lnas/hide-code/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-kfl9qvks
         cwd: /tmp/pip-install-wja8lnas/hide-code/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-wja8lnas/hide-code/setup.py", line 9, in <module>
        import notebook
    ModuleNotFoundError: No module named 'notebook'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

The problem is that `setup.py` itself imports `notebook`. The `pip install hide_code[all]` approach doesn't help, because that doesn't install `notebook` until `setup()` is called, but `setup.py` tries to import `notebook` before calling `setup()`.

The only place the `notebook` package is used in `setup.py` is to perform the post-installation steps that install and enable the jupyter extension. But the installation instructions in the README tell us to do that manually, so I wonder if the setup script even needs to do this at all.

If you do still want the setup script to try installing and enabling the extension, I suggest following the pattern used in https://github.com/textpipe/textpipe/blob/bc6a0828e9114da9a498a40af0fda214be74c065/setup.py, where the third-party package is imported in a `try` block, and if it can't be imported it simply skips the post-install steps.

**Comment by kirbs-** [comment]
Resolved in 0.7.0 release.
